version: '3'
services:
  app:
    build: .
    network_mode: "host"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: shop
      MYSQL_USER: root
      MYSQL_PASSWORD: rifki
      MYSQL_ROOT_PASSWORD: rifkhi
